2021-03-29 13:29:04,350 apscheduler.scheduler Scheduler started
2021-03-29 13:29:04,352 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:29:04,353 apscheduler.scheduler No jobs; waiting until a job is added
2021-03-29 13:30:27,117 apscheduler.scheduler Scheduler started
2021-03-29 13:30:27,118 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:30:27,119 apscheduler.scheduler No jobs; waiting until a job is added
2021-03-29 13:30:27,948 werkzeug  * Restarting with stat
2021-03-29 13:30:30,314 apscheduler.scheduler Scheduler started
2021-03-29 13:30:30,316 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:30:30,316 apscheduler.scheduler No jobs; waiting until a job is added
2021-03-29 13:30:30,921 werkzeug  * Debugger is active!
2021-03-29 13:30:30,948 werkzeug  * Debugger PIN: 141-834-372
2021-03-29 13:30:30,957 werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-03-29 13:30:31,843 werkzeug 127.0.0.1 - - [29/Mar/2021 13:30:31] "[37mGET / HTTP/1.1[0m" 200 -
2021-03-29 13:30:51,208 werkzeug 127.0.0.1 - - [29/Mar/2021 13:30:51] "[37mGET / HTTP/1.1[0m" 200 -
2021-03-29 13:30:58,080 werkzeug 127.0.0.1 - - [29/Mar/2021 13:30:58] "[32mPOST / HTTP/1.1[0m" 302 -
2021-03-29 13:30:58,121 werkzeug 127.0.0.1 - - [29/Mar/2021 13:30:58] "[37mGET /system HTTP/1.1[0m" 200 -
2021-03-29 13:31:01,578 werkzeug 127.0.0.1 - - [29/Mar/2021 13:31:01] "[37mGET / HTTP/1.1[0m" 200 -
2021-03-29 13:31:15,328 werkzeug 127.0.0.1 - - [29/Mar/2021 13:31:15] "[32mPOST / HTTP/1.1[0m" 302 -
2021-03-29 13:31:15,352 werkzeug 127.0.0.1 - - [29/Mar/2021 13:31:15] "[37mGET /system HTTP/1.1[0m" 200 -
2021-03-29 13:31:23,615 werkzeug 127.0.0.1 - - [29/Mar/2021 13:31:23] "[35m[1mPOST /system HTTP/1.1[0m" 500 -
2021-03-29 13:31:23,712 werkzeug 127.0.0.1 - - [29/Mar/2021 13:31:23] "[37mGET /system?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
2021-03-29 13:31:23,733 werkzeug 127.0.0.1 - - [29/Mar/2021 13:31:23] "[37mGET /system?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
2021-03-29 13:31:23,749 werkzeug 127.0.0.1 - - [29/Mar/2021 13:31:23] "[37mGET /system?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
2021-03-29 13:31:23,980 werkzeug 127.0.0.1 - - [29/Mar/2021 13:31:23] "[37mGET /system?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
2021-03-29 13:31:24,012 werkzeug 127.0.0.1 - - [29/Mar/2021 13:31:24] "[37mGET /system?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-03-29 13:31:24,172 werkzeug 127.0.0.1 - - [29/Mar/2021 13:31:24] "[37mGET /system?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
2021-03-29 13:32:02,077 werkzeug  * Detected change in 'c:\\Users\\Benedikt\\OneDrive\\Universität\\Master\\03_2Semester\\Projektseminar\\PJS_Code_v2\\flasktest\\run_middleware.py', reloading
2021-03-29 13:32:02,779 werkzeug  * Restarting with stat
2021-03-29 13:32:14,827 apscheduler.scheduler Scheduler started
2021-03-29 13:32:14,828 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:32:14,828 apscheduler.scheduler No jobs; waiting until a job is added
2021-03-29 13:32:15,503 werkzeug  * Restarting with stat
2021-03-29 13:32:17,550 apscheduler.scheduler Scheduler started
2021-03-29 13:32:17,551 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:32:17,552 apscheduler.scheduler No jobs; waiting until a job is added
2021-03-29 13:32:18,136 werkzeug  * Debugger is active!
2021-03-29 13:32:18,164 werkzeug  * Debugger PIN: 141-834-372
2021-03-29 13:32:18,171 werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-03-29 13:32:22,910 werkzeug 127.0.0.1 - - [29/Mar/2021 13:32:22] "[37mGET / HTTP/1.1[0m" 200 -
2021-03-29 13:32:27,015 werkzeug 127.0.0.1 - - [29/Mar/2021 13:32:27] "[32mPOST / HTTP/1.1[0m" 302 -
2021-03-29 13:32:27,051 werkzeug 127.0.0.1 - - [29/Mar/2021 13:32:27] "[37mGET /system HTTP/1.1[0m" 200 -
2021-03-29 13:32:33,120 werkzeug 127.0.0.1 - - [29/Mar/2021 13:32:33] "[32mPOST /system HTTP/1.1[0m" 302 -
2021-03-29 13:32:33,150 werkzeug 127.0.0.1 - - [29/Mar/2021 13:32:33] "[37mGET /choice HTTP/1.1[0m" 200 -
2021-03-29 13:32:36,926 werkzeug 127.0.0.1 - - [29/Mar/2021 13:32:36] "[32mPOST /choice HTTP/1.1[0m" 302 -
2021-03-29 13:32:36,984 werkzeug 127.0.0.1 - - [29/Mar/2021 13:32:36] "[37mGET /erp/myfactory HTTP/1.1[0m" 200 -
2021-03-29 13:33:11,097 werkzeug 127.0.0.1 - - [29/Mar/2021 13:33:11] "[37mPOST /erp/myfactory HTTP/1.1[0m" 200 -
2021-03-29 13:35:21,675 apscheduler.scheduler Scheduler started
2021-03-29 13:35:21,677 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:35:21,677 apscheduler.scheduler No jobs; waiting until a job is added
2021-03-29 13:35:22,576 werkzeug  * Restarting with stat
2021-03-29 13:35:25,218 apscheduler.scheduler Scheduler started
2021-03-29 13:35:25,220 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:35:25,220 apscheduler.scheduler No jobs; waiting until a job is added
2021-03-29 13:35:25,858 werkzeug  * Debugger is active!
2021-03-29 13:35:25,879 werkzeug  * Debugger PIN: 141-834-372
2021-03-29 13:35:25,890 werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-03-29 13:35:28,169 werkzeug 127.0.0.1 - - [29/Mar/2021 13:35:28] "[37mGET / HTTP/1.1[0m" 200 -
2021-03-29 13:35:37,205 werkzeug 127.0.0.1 - - [29/Mar/2021 13:35:37] "[32mPOST / HTTP/1.1[0m" 302 -
2021-03-29 13:35:37,236 werkzeug 127.0.0.1 - - [29/Mar/2021 13:35:37] "[37mGET /system HTTP/1.1[0m" 200 -
2021-03-29 13:35:43,697 werkzeug 127.0.0.1 - - [29/Mar/2021 13:35:43] "[32mPOST /system HTTP/1.1[0m" 302 -
2021-03-29 13:35:43,750 werkzeug 127.0.0.1 - - [29/Mar/2021 13:35:43] "[37mGET /choice HTTP/1.1[0m" 200 -
2021-03-29 13:35:48,530 werkzeug 127.0.0.1 - - [29/Mar/2021 13:35:48] "[32mPOST /choice HTTP/1.1[0m" 302 -
2021-03-29 13:35:48,594 werkzeug 127.0.0.1 - - [29/Mar/2021 13:35:48] "[37mGET /erp/myfactory HTTP/1.1[0m" 200 -
2021-03-29 13:35:56,757 apscheduler.scheduler Added job "MiddlewareControl.job_interval_updates" to job store "default"
2021-03-29 13:35:56,758 werkzeug 127.0.0.1 - - [29/Mar/2021 13:35:56] "[32mPOST /erp/myfactory HTTP/1.1[0m" 302 -
2021-03-29 13:35:56,759 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:35:56,759 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:36:26.757445+02:00 (in 29.997982 seconds)
2021-03-29 13:35:56,782 werkzeug 127.0.0.1 - - [29/Mar/2021 13:35:56] "[37mGET / HTTP/1.1[0m" 200 -
2021-03-29 13:36:26,765 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:36:26,768 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:36:26 CEST)" (scheduled at 2021-03-29 13:36:26.757445+02:00)
2021-03-29 13:36:26,770 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:36:56.757445+02:00 (in 29.990131 seconds)
2021-03-29 13:36:26,870 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:36:27,153 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:36:27,219 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:36:56 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 196, in updates
    return pdf_created, article_numbers , done
NameError: name 'article_numbers' is not defined
2021-03-29 13:36:56,772 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:36:56,772 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:37:26.757445+02:00 (in 29.985193 seconds)
2021-03-29 13:36:56,772 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:37:26 CEST)" (scheduled at 2021-03-29 13:36:56.757445+02:00)
2021-03-29 13:36:56,869 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:36:57,530 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:36:57,621 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:37:26 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: too many values to unpack (expected 2)
2021-03-29 13:37:26,770 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:37:26,770 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:37:56.757445+02:00 (in 29.986639 seconds)
2021-03-29 13:37:26,770 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:37:56 CEST)" (scheduled at 2021-03-29 13:37:26.757445+02:00)
2021-03-29 13:37:26,872 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:37:27,066 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:37:27,158 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:37:56 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: too many values to unpack (expected 2)
2021-03-29 13:37:56,768 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:37:56,768 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:38:26.757445+02:00 (in 29.989243 seconds)
2021-03-29 13:37:56,768 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:38:26 CEST)" (scheduled at 2021-03-29 13:37:56.757445+02:00)
2021-03-29 13:37:56,867 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:37:57,440 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:37:57,541 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:38:26 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: too many values to unpack (expected 2)
2021-03-29 13:38:26,764 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:38:26,765 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:38:56.757445+02:00 (in 29.992010 seconds)
2021-03-29 13:38:26,766 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:38:56 CEST)" (scheduled at 2021-03-29 13:38:26.757445+02:00)
2021-03-29 13:38:26,863 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:38:27,054 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:38:27,151 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:38:56 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: too many values to unpack (expected 2)
2021-03-29 13:38:56,774 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:38:56,775 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:39:26.757445+02:00 (in 29.981976 seconds)
2021-03-29 13:38:56,776 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:39:26 CEST)" (scheduled at 2021-03-29 13:38:56.757445+02:00)
2021-03-29 13:38:56,881 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:38:57,496 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:38:57,597 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:39:26 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: too many values to unpack (expected 2)
2021-03-29 13:39:26,759 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:39:26,760 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:39:56.757445+02:00 (in 29.997266 seconds)
2021-03-29 13:39:26,761 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:39:56 CEST)" (scheduled at 2021-03-29 13:39:26.757445+02:00)
2021-03-29 13:39:26,862 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:39:27,464 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:39:27,559 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:39:56 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: too many values to unpack (expected 2)
2021-03-29 13:39:56,769 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:39:56,770 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:40:26.757445+02:00 (in 29.988210 seconds)
2021-03-29 13:39:56,770 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:40:26 CEST)" (scheduled at 2021-03-29 13:39:56.757445+02:00)
2021-03-29 13:39:56,872 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:39:57,078 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:39:57,166 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:40:26 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: too many values to unpack (expected 2)
2021-03-29 13:40:26,768 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:40:26,769 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:40:56.757445+02:00 (in 29.987530 seconds)
2021-03-29 13:40:26,770 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:40:56 CEST)" (scheduled at 2021-03-29 13:40:26.757445+02:00)
2021-03-29 13:40:26,870 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:40:27,079 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:40:27,152 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:40:56 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: too many values to unpack (expected 2)
2021-03-29 13:40:56,767 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:40:56,767 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:41:26.757445+02:00 (in 29.989799 seconds)
2021-03-29 13:40:56,767 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:41:26 CEST)" (scheduled at 2021-03-29 13:40:56.757445+02:00)
2021-03-29 13:40:56,887 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:40:57,126 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:40:57,236 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:41:26 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: too many values to unpack (expected 2)
2021-03-29 13:41:26,771 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:41:26,771 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:41:56.757445+02:00 (in 29.986310 seconds)
2021-03-29 13:41:26,771 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:41:56 CEST)" (scheduled at 2021-03-29 13:41:26.757445+02:00)
2021-03-29 13:41:26,867 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:41:27,108 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:41:27,179 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:41:56 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: too many values to unpack (expected 2)
2021-03-29 13:41:56,768 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:41:56,768 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:42:26.757445+02:00 (in 29.988602 seconds)
2021-03-29 13:41:56,768 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:42:26 CEST)" (scheduled at 2021-03-29 13:41:56.757445+02:00)
2021-03-29 13:41:56,862 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:41:57,086 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:41:57,176 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:42:26 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: too many values to unpack (expected 2)
2021-03-29 13:42:26,763 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:42:26,764 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:42:56.757445+02:00 (in 29.993224 seconds)
2021-03-29 13:42:26,765 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:42:56 CEST)" (scheduled at 2021-03-29 13:42:26.757445+02:00)
2021-03-29 13:42:26,878 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:42:27,099 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:42:27,169 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:42:56 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: too many values to unpack (expected 2)
2021-03-29 13:45:22,356 apscheduler.scheduler Scheduler started
2021-03-29 13:45:22,364 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:45:22,365 apscheduler.scheduler No jobs; waiting until a job is added
2021-03-29 13:45:23,167 werkzeug  * Restarting with stat
2021-03-29 13:45:25,798 apscheduler.scheduler Scheduler started
2021-03-29 13:45:25,800 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:45:25,801 apscheduler.scheduler No jobs; waiting until a job is added
2021-03-29 13:45:26,666 werkzeug  * Debugger is active!
2021-03-29 13:45:26,760 werkzeug  * Debugger PIN: 141-834-372
2021-03-29 13:45:26,780 werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2021-03-29 13:45:26,925 werkzeug 127.0.0.1 - - [29/Mar/2021 13:45:26] "[37mGET / HTTP/1.1[0m" 200 -
2021-03-29 13:45:52,815 werkzeug 127.0.0.1 - - [29/Mar/2021 13:45:52] "[32mPOST / HTTP/1.1[0m" 302 -
2021-03-29 13:45:52,847 werkzeug 127.0.0.1 - - [29/Mar/2021 13:45:52] "[37mGET /system HTTP/1.1[0m" 200 -
2021-03-29 13:46:02,088 werkzeug 127.0.0.1 - - [29/Mar/2021 13:46:02] "[32mPOST /system HTTP/1.1[0m" 302 -
2021-03-29 13:46:02,120 werkzeug 127.0.0.1 - - [29/Mar/2021 13:46:02] "[37mGET /choice HTTP/1.1[0m" 200 -
2021-03-29 13:46:22,653 werkzeug 127.0.0.1 - - [29/Mar/2021 13:46:22] "[32mPOST /choice HTTP/1.1[0m" 302 -
2021-03-29 13:46:22,717 werkzeug 127.0.0.1 - - [29/Mar/2021 13:46:22] "[37mGET /erp/myfactory HTTP/1.1[0m" 200 -
2021-03-29 13:46:29,063 apscheduler.scheduler Added job "MiddlewareControl.job_interval_updates" to job store "default"
2021-03-29 13:46:29,064 werkzeug 127.0.0.1 - - [29/Mar/2021 13:46:29] "[32mPOST /erp/myfactory HTTP/1.1[0m" 302 -
2021-03-29 13:46:29,065 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:46:29,067 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:46:59.062408+02:00 (in 29.995002 seconds)
2021-03-29 13:46:29,085 werkzeug 127.0.0.1 - - [29/Mar/2021 13:46:29] "[37mGET / HTTP/1.1[0m" 200 -
2021-03-29 13:46:59,077 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:46:59,078 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:46:59 CEST)" (scheduled at 2021-03-29 13:46:59.062408+02:00)
2021-03-29 13:46:59,079 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:47:29.062408+02:00 (in 29.984381 seconds)
2021-03-29 13:46:59,180 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:46:59,778 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:46:59,875 root Exportierte Anlagen: System: myfactory; Artikel Nummern: A011117
2021-03-29 13:46:59,875 root Update: System: myfactory; Artikel Nummern: A011116
2021-03-29 13:46:59,875 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:47:29 CEST)" executed successfully
2021-03-29 13:47:29,080 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:47:29,080 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:47:59.062408+02:00 (in 29.982286 seconds)
2021-03-29 13:47:29,080 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:47:59 CEST)" (scheduled at 2021-03-29 13:47:29.062408+02:00)
2021-03-29 13:47:29,181 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:47:29,370 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:47:29,432 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:47:59 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, article_numbers, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: not enough values to unpack (expected 3, got 2)
2021-03-29 13:47:59,071 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:47:59,071 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:48:29.062408+02:00 (in 29.991365 seconds)
2021-03-29 13:47:59,071 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:48:29 CEST)" (scheduled at 2021-03-29 13:47:59.062408+02:00)
2021-03-29 13:47:59,170 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:47:59,391 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:47:59,491 root Exportierte Anlagen: System: myfactory; Artikel Nummern: A011117
2021-03-29 13:47:59,492 root Update: System: myfactory; Artikel Nummern: A011116
2021-03-29 13:47:59,492 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:48:29 CEST)" executed successfully
2021-03-29 13:48:29,078 apscheduler.scheduler Looking for jobs to run
2021-03-29 13:48:29,078 apscheduler.scheduler Next wakeup is due at 2021-03-29 13:48:59.062408+02:00 (in 29.983902 seconds)
2021-03-29 13:48:29,079 apscheduler.executors.default Running job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:48:59 CEST)" (scheduled at 2021-03-29 13:48:29.062408+02:00)
2021-03-29 13:48:29,182 urllib3.connectionpool Starting new HTTPS connection (1): cloud.myfactory.com:443
2021-03-29 13:48:29,415 urllib3.connectionpool https://cloud.myfactory.com:443 "GET /myfactory/odata_lusajejalimimajoyuso52/Artikel HTTP/1.1" 200 110459
2021-03-29 13:48:29,526 apscheduler.executors.default Job "MiddlewareControl.job_interval_updates (trigger: interval[0:00:30], next run at: 2021-03-29 13:48:59 CEST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Benedikt\AppData\Local\Programs\Python\Python38\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 79, in job_interval_updates
    self.init_updates()
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 105, in init_updates
    result, ids, done = self.updates(self.erp, self.client, last_update_time, actual_update_time, self.device_export)
  File "c:\Users\Benedikt\OneDrive\Universität\Master\03_2Semester\Projektseminar\PJS_Code_v2\flasktest\middleware.py", line 195, in updates
    pdf_created, article_numbers, done = updateMyFactory.update(last_update_time=last_update_time, actual_update_time=actual_update_time)
ValueError: not enough values to unpack (expected 3, got 2)
2021-03-29 13:48:56,874 werkzeug  * Detected change in 'c:\\Users\\Benedikt\\OneDrive\\Universität\\Master\\03_2Semester\\Projektseminar\\PJS_Code_v2\\flasktest\\middleware.py', reloading
2021-03-29 13:48:57,594 werkzeug  * Restarting with stat
